version: 2

project_name: spotify-playlist

builds:
  - id: spotify-playlist
    main: ./cmd/spotify
    binary: spotify-playlist
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.defaultClientID={{ .Env.SPOTIFY_CLIENT_ID }} -X main.version={{ .Version }}

archives:
  - id: archive
    ids:
      - spotify-playlist
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: spotify-playlist
    ids:
      - archive
    repository:
      owner: dh85
      name: homebrew-tap
      token: "{{ .Env.PUBLISH_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/dh85/spotify-playlist
    description: CLI tool to display formatted Spotify playlists.
    commit_msg_template: "brew: update {{ .ProjectName }} to {{ .Tag }}"
    install: |
      bin.install "spotify-playlist"
    test: |
      system "#{bin}/spotify-playlist", "--version"

scoops:
  - name: spotify-playlist
    ids:
      - archive
    repository:
      owner: dh85
      name: scoop-bucket
      token: "{{ .Env.PUBLISH_GITHUB_TOKEN }}"
    homepage: https://github.com/dh85/spotify-playlist
    description: CLI tool to display formatted Spotify playlists.
    commit_msg_template: "scoop: update {{ .ProjectName }} to {{ .Tag }}"
