version: 2

project_name: spotify-playlist

builds:
  - main: ./cmd/spotify
    binary: spotify-playlist
    ldflags:
      - -s -w
      - -X main.defaultClientID={{ .Env.SPOTIFY_CLIENT_ID }}
      - -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew:
  - repository:
      owner: dh85
      name: homebrew-tap
      token: "{{ .Env.PUBLISH_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/dh85/spotify-playlist"
    description: "CLI tool to display formatted Spotify playlists"
    license: "MIT"
    install: |
      bin.install "spotify-playlist"

scoops:
  - repository:
      owner: dh85
      name: scoop-bucket
      token: "{{ .Env.PUBLISH_GITHUB_TOKEN }}"
    homepage: "https://github.com/dh85/spotify-playlist"
    description: "CLI tool to display formatted Spotify playlists"
    license: "MIT"
